format_version: 10
pipelines:
  ml_fc:
    group: latam02-ml
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      repo:
        git: https://github.com/latam02/ml.git
        shallow_clone: false
        auto_update: true
        branch: task8_fc
    stages:
    - UnitTest:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit:
            resources:
              - test
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - pip install -r requirements-dev.txt --no-cache-dir
                command: bash
                run_if: passed
