format_version: 10
pipelines:
  test:
    group: latam02-ml
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      repo:
        git: https://github.com/latam02/ml.git
        username: lcarrietas
        shallow_clone: false
        auto_update: true
        branch: Task7_docker-hub
    stages:
    - Step1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          iCu:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - I
                - see
                - you
                command: echo
                run_if: passed