version: '3.3'

services:
    postgresql:
        image: postgres:14.0-alpine
        volumes:
         - postgres_data:/var/lib/postgresql/data
        container_name: postgresql
        environment:
         POSTGRES_USER: 'atlatam'
         POSTGRES_PASSWORD: 'atlatam'
         POSTGRES_DB: 'atlatam'
        ports:
         - "5432:5432"

    app:
      image: machine_learning_fc:1.0
      volumes:
        - ml:/usr/src/app
      ports:
        - "8000:8000"
      env_file:
        - ./.env.dev
      depends_on:
        - postgresql

volumes:
    postgres_data:
    ml:
