# Generated by Django 3.2.5 on 2021-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognizer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlAssets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
